project_id = "ghmjjrmunjvuavnxukgi"

[functions.mercadopago-checkout]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.log-login]
verify_jwt = false

[functions.notify-session-revoked]
verify_jwt = false
